apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-template-test
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: k8s-template-test
  template:
    metadata:
      labels:
          app: k8s-template-test
    spec:
      restartPolicy: Always
      containers:
        - name: k8s-template-test
          image: registry.digitalocean.com/trydmii-cr/k8s-template-test:v1
          ports:
            - containerPort: 8000